project_name: wtx

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: wtx
    main: ./cmd/wtx
    binary: wtx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: wtx
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: darkLord19
    name: wtx
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: wtx
    repository:
      owner: darkLord19
      name: homebrew-tap
    homepage: "https://github.com/darkLord19/wtx"
    description: "Git worktree workspace manager"
    license: "MIT"
    install: |
      bin.install "wtx"
    test: |
      system "#{bin}/wtx", "--version"
